In [3]:
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds

In [2]:
TEST = r'C:\Users\arish\open-source\psi-detection\data\intermediate\H.sapiens100\test.csv'
TRAIN = r'C:\Users\arish\open-source\psi-detection\data\intermediate\H.sapiens100\train.csv'
VALID = r'C:\Users\arish\open-source\psi-detection\data\intermediate\H.sapiens100\valid.csv'

In [4]:
dataset, info = tfds.load('imdb_reviews', with_info=True,
                          as_supervised=True)
train_dataset, test_dataset = dataset['train'], dataset['test']

In [26]:
VOCAB_SIZE = 1000
encoder = tf.keras.layers.TextVectorization(
    max_tokens=VOCAB_SIZE)
encoder.adapt(train_dataset.map(lambda text, label: text))

In [15]:
samples = list(train_dataset.take(126))

In [36]:
a = [x[0] for x in samples]

In [38]:
a[:5]

[<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">,
 <tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. Howev

In [35]:
tf.convert_to_tensor(a).shape

TensorShape([126])

In [32]:
encoder(a)

<tf.Tensor: shape=(126, 861), dtype=int64, numpy=
array([[ 11,  14,  34, ...,   0,   0,   0],
       [ 10,  26,  75, ...,   0,   0,   0],
       [  1,   1,   2, ...,   0,   0,   0],
       ...,
       [  3,  32, 141, ...,   0,   0,   0],
       [  2,   1,   1, ...,   0,   0,   0],
       [ 10,  63, 153, ...,   0,   0,   0]], dtype=int64)>